name: Deploy to Production

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trae-api-gateway:latest,${{ secrets.DOCKERHUB_USERNAME }}/trae-api-gateway:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trae-user-service:latest,${{ secrets.DOCKERHUB_USERNAME }}/trae-user-service:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Event Ticket Service
        uses: docker/build-push-action@v4
        with:
          context: ./event-ticket-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trae-event-ticket-service:latest,${{ secrets.DOCKERHUB_USERNAME }}/trae-event-ticket-service:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Payment Service
        uses: docker/build-push-action@v4
        with:
          context: ./payment-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trae-payment-service:latest,${{ secrets.DOCKERHUB_USERNAME }}/trae-payment-service:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Notification Service
        uses: docker/build-push-action@v4
        with:
          context: ./notification-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trae-notification-service:latest,${{ secrets.DOCKERHUB_USERNAME }}/trae-notification-service:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml,prometheus.yml,grafana/provisioning/"
          target: "/opt/trae"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/trae
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
            docker-compose pull
            docker-compose up -d